version: '3.7'

services:
  user_db:
    build: ./user
    container_name: user_db
    restart: always

  product_db:
    build: ./product
    container_name: product_db
    restart: always

  order_db:
    build: ./order
    container_name: order_db
    restart: always