version: '3.8'

services:
  mongo:
      image: mongo
      container_name: mongo-product
      restart: always
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: root
      ports:
        - 27018:27018
      volumes:
        - mongo-data:/data/db

volumes:
  mongo-data:
    driver: local
